const ActionTypes = {
    GET_ALL_PRODUCTS_LOADING: 'GET_ALL_PRODUCTS_LOADING',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAIL: 'GET_ALL_PRODUCTS_FAIL',
    GET_PRODUCT_INFO_LOADING: 'GET_PRODUCT_INFO_LOADING',
    GET_PRODUCT_INFO_SUCCESS: 'GET_PRODUCT_INFO_SUCCESS',
    GET_PRODUCT_INFO_FAIL: 'GET_PRODUCT_INFO_FAIL',
    GET_CART_ITEMS_LOADING: 'GET_CART_ITEMS_LOADING',
    GET_CART_ITEMS_SUCCESS: 'GET_CART_ITEMS_SUCCESS', 
    GET_CART_ITEMS_FAIL: 'GET_CART_ITEMS_FAIL',
    GET_PAYMENTS_HISTORY_LOADING: 'GET_PAYMENTS_HISTORY_LOADING',
    GET_PAYMENTS_HISTORY_SUCCESS: 'GET_PAYMENTS_HISTORY_SUCCESS',
    GET_PAYMENTS_HISTORY_FAIL: 'GET_PAYMENTS_HISTORY_FAIL',
}

export default ActionTypes